name: Run Cucumber Tests

on: 

  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Run Tests with Maven
      run: mvn clean test -Denv=${{ github.event.inputs.env}}

    - name: Upload Cucumber Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: target/cucumber-report.html

